dubbo:
  application:
    name: dubbo-producer  #dubbo的注册的服务名, 唯一性
    version: 1.0.0  # 服务提供的版本
  registry:
    address: zookeeper://117.62.217.89:2181  # 注册中心的地址
    timeout: 100000
  protocols:
    dubbo:
      #协议名称
      name: dubbo
      #服务暴露端口
      port: -1
#    http:
#      name: http
#      port: 8080
#      server: jetty
  scan:
    base-packages: com.mj.learn.dubbo.provider # 接口实现类的包名
  config-center:
    timeout: 60000
server:
  port: 8082