dubbo:
  application:
    name: dubbo-consumer  #dubbo的注册的服务名, 唯一性
    version: 1.0.0  # 服务提供的版本
  registry:
    address: zookeeper://117.62.217.89:2181  # 注册中心的地址
    timeout: 100000
  config-center:
    timeout: 60000
  consumer:
    check: false
    timeout: 60000
server:
  port: 8081