dubbo:
  application:
    name: dubbo-producer  #dubbo的注册的服务名, 唯一性
    version: 1.0.0  # 服务提供的版本
  registry:
    address: zookeeper://49.234.61.67:2181  # 注册中心的地址
  protocol:
    #协议名称
    name: dubbo
    #服务暴露端口
    port: 20881
  consumer:
    check: false
server:
  port: 8081